const store=require('../../utils/store');const sync=require('../../utils/sync');
Page({
 data:{couple:null,code:'',busy:false,cloudReady:false,partner:null,partnerName:'我爱的 TA',days:0,rewardResult:'',rewardDone:false},
 async onShow(){this.setData({cloudReady:sync.cloudReady()});await sync.pull();this.refresh();},
 refresh(){let s=store.getState(),own=s.couple,partner=sync.getPartnerState();if(own&&partner&&!own.since){const since=store.dateKey(new Date(s.installedAt||Date.now()));store.update(x=>{x.couple={...x.couple,since};});s=store.getState();own=s.couple;sync.push();}const couple=own&&partner?{...own,status:'bound'}:own;const partnerName=partner&&partner.profile&&partner.profile.nickname||own&&own.partnerName||'我爱的 TA';const since=couple&&couple.since?new Date(`${couple.since}T00:00:00`):null;const days=since?Math.max(1,Math.floor((new Date().setHours(0,0,0,0)-since.getTime())/86400000)+1):0;const reward=s.weeklyReward&&s.weeklyReward.week===store.weekKey()?s.weeklyReward:null;this.setData({couple,partner,partnerName,days,rewardResult:reward?reward.result:'',rewardDone:Boolean(reward)});},
 input(e){this.setData({code:e.detail.value.trim().toUpperCase()});},
 async generate(){if(!sync.cloudReady()){wx.showToast({title:'请先配置云开发环境',icon:'none'});return;}this.setData({busy:true});try{const result=await sync.createInvite(),since=store.dateKey();store.update(s=>{s.couple={status:'inviting',inviteCode:result.code,spaceId:result.spaceId,partnerName:'等待对方加入',since};});await sync.push();this.refresh();}catch(e){wx.showToast({title:'生成失败，请稍后重试',icon:'none'});}finally{this.setData({busy:false});}},
 async join(){if(this.data.code.length!==6){wx.showToast({title:'请输入6位邀请码',icon:'none'});return;}if(!sync.cloudReady()){wx.showToast({title:'请先配置云开发环境',icon:'none'});return;}this.setData({busy:true});try{const result=await sync.joinInvite(this.data.code),since=store.dateKey();store.update(s=>{s.couple={status:'bound',inviteCode:this.data.code,spaceId:result.spaceId,partnerName:'我爱的 TA',since};});await sync.push();this.refresh();wx.showToast({title:'绑定成功'});}catch(e){wx.showToast({title:'邀请码无效或已过期',icon:'none'});}finally{this.setData({busy:false});}},
 reward(){if(this.data.rewardDone)return;const a=store.getState().rewards||[];if(!a.length)return;const result=a[Math.floor(Math.random()*a.length)];store.update(s=>{s.weeklyReward={week:store.weekKey(),result,createdAt:Date.now()};});sync.push();this.refresh();wx.showModal({title:'本周情侣奖励',content:result,showCancel:false});},
 sinceChange(e){const since=e.detail.value;store.update(s=>{s.couple={...s.couple,since};});sync.push();this.refresh();wx.showToast({title:'相伴起点已更新'});},
 profile(){wx.navigateTo({url:'/pages/profile/profile'});},report(){wx.navigateTo({url:'/pages/report/report'});},
 unbind(){wx.showModal({title:'解除情侣绑定？',content:'双方本地记录会保留，相伴天数将停止累计。',success:async r=>{if(r.confirm){try{if(sync.cloudReady())await sync.unbind();}finally{store.update(s=>{s.couple=null;});this.refresh();}}}});}
});
