const {dishes}=require('../../utils/dishes');const dishArt=require('../../utils/dish-art');const store=require('../../utils/store');const sync=require('../../utils/sync');
const LIMIT=3;
Page({
 data:{today:'',plan:'还没决定',latest:null,partnerToday:null,couple:null,showPicker:false,result:null,resultStyle:'',rolling:false,remaining:LIMIT,confirmed:false},
 async onShow(){await sync.pull();this.load();},
 load(){const s=store.getState(),today=store.dateKey(),latest=s.logs.find(x=>x.date===today)||null,partner=sync.getPartnerState(),partnerToday=partner&&partner.logs&&partner.logs.find(x=>x.date===today)||null;const used=s.draws.filter(x=>x.date===today&&x.target==='self').length;this.setData({today,plan:s.plans[today]||'还没决定',latest,partnerToday,couple:s.couple,remaining:Math.max(0,LIMIT-used),confirmed:false});},
 decide(){if(this.data.remaining<=0){wx.showToast({title:'今天已经认真选过啦',icon:'none'});return;}this.setData({showPicker:true,result:null,confirmed:false});this.pick();},
 pick(){if(this.data.rolling||this.data.remaining<=0)return;const s=store.getState(),budget=Number(s.profile.budget)||35,dislikes=s.profile.dislikes||'';let pool=[...dishes,...s.customDishes].filter(x=>Number(x.price)<=budget&&!dislikes.split(/[、,，\s]+/).filter(Boolean).some(k=>x.name.includes(k)));if(!pool.length)pool=dishes.filter(x=>Number(x.price)<=budget);this.setData({rolling:true,result:null});setTimeout(()=>{const picked=pool[Math.floor(Math.random()*pool.length)],drawId=Date.now(),result={...picked,drawId};store.update(state=>state.draws.unshift({id:drawId,date:store.dateKey(),dish:result.name,cuisine:result.cuisine,target:'self',accepted:false}));const remaining=Math.max(0,this.data.remaining-1);this.setData({result,resultStyle:dishArt.styleFor(result),rolling:false,remaining});sync.push();},550);},
 accept(){if(!this.data.result||this.data.confirmed)return;const r=this.data.result;store.update(s=>{const exists=s.logs.some(x=>String(x.sourceDrawId)===String(r.drawId));if(!exists)s.logs.unshift({id:Date.now(),sourceDrawId:r.drawId,date:store.dateKey(),mealTime:'12:00',dish:r.name,actualDish:r.name,cuisine:r.cuisine,mealType:'外卖',rating:0,note:'',tags:[],privacy:'couple',createdAt:Date.now()});const d=s.draws.find(x=>String(x.id)===String(r.drawId));if(d)d.accepted=true;});this.setData({confirmed:true});sync.push();wx.showToast({title:'已记下这一餐'});setTimeout(()=>{this.setData({showPicker:false});this.load();},650);},
 close(){if(!this.data.rolling)this.setData({showPicker:false});},noop(){},goPlan(){wx.navigateTo({url:'/pages/plan/plan'});},goRecord(){wx.switchTab({url:'/pages/logs/logs'});}
});
